apiVersion: v1
kind: ConfigMap
metadata:
  name: dealership-config
data:
  DJANGO_DEBUG: "false"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_DB_PATH: /data/db.sqlite3
  backend_url: http://dealer-api:3030
  sentiment_analyzer_url: http://sentiment:5050
  MONGO_URL: mongodb://mongo:27017/dealershipsDB
